from node

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

VOLUME /artillery

COPY load-user/ load-user/

WORKDIR load-user/

ENTRYPOINT ["./node_modules/artillery/bin/artillery"]
CMD ["run", "game.yaml"]
