apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: "demo2020-load-test-websocket"
spec:
  replicas: {{ replicas }}
  selector:
   matchLabels:
     app: demo2020-load-test-websocket
  template:
    metadata:
      labels:
        app: demo2020-load-test-websocket
    spec:
      containers:
       - image: {{ image }}
         imagePullPolicy: Always
         name: demo2020-load-test-websocket
         env:
         - name: USERS
           valueFrom:
             configMapKeyRef:
               name: load-configmap
               key: users
         - name: SOCKET_ADDRESS
           valueFrom:
             configMapKeyRef:
               name: load-configmap
               key: socket_address
         - name: DURATION
           valueFrom:
             configMapKeyRef:
               name: load-configmap
               key: duration

         - name: MOVEMENT
           valueFrom:
             configMapKeyRef:
               name: load-configmap
               key: movement