apiVersion: v1
kind: Template

metadata:
  name: demo4-load-test-websocket

parameters:
  - name: APPLICATION_NAME
    value: demo4-load-test-websocket
    required: true

  - name: DURATION
    value: '100'
    description: Duration of Load Test
    required: true

  - name: USERS_PER_POD
    value: '1' 
    description: Number of Virtual Users per pod
    required: true

  - name: REPLICAS
    value: '1'
    description: Number of Replicas of Load Test
    required: true

  - name: SOCKET_ADDRESS
    value: 'ws://'
    required: true
  
  - name: IMAGE_REPOSITORY
    displayName: Image Repository (quay.io/user/demo4-load-test-websocket:latest)
    value: quay.io/redhatdemo/demo4-load-test-websocket:latest
    required: true

objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: load-configmap
    data:
      duration: "${DURATION}"
      socket_address: "${SOCKET_ADDRESS}"
      users: "${USERS_PER_POD}"

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      replicas: ${REPLICAS}
      selector:
        app: ${APPLICATION_NAME}
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          containers:
            - image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              env:
              - name: USERS
                valueFrom:
                configMapKeyRef:
                  name: load-configmap
                  key: users
              - name: SOCKET_ADDRESS
                valueFrom:
                configMapKeyRef:
                  name: load-configmap
                  key: socket_address
              - name: DURATION
                valueFrom:
                configMapKeyRef:
                  name: load-configmap
                  key: duration
                
              
      triggers:
        - type: ConfigChange