apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ namespace }}
  name: "demo4-load-test-websocket-{{ ansible_date_time.iso8601_micro | to_uuid }}"
spec:
  template:
    metadata:
      labels:
        app: demo4-load-test-websocket
    spec:
      containers:
        - image: {{ image }}
          imagePullPolicy: Always
          name: demo4-load-test-websocket
          env:
          - name: USERS
            valueFrom:
              configMapKeyRef:
                name: load-configmap
                key: users
          - name: SOCKET_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: load-configmap
                key: socket_address
          - name: DURATION
            valueFrom:
              configMapKeyRef:
                name: load-configmap
                key: duration
      restartPolicy: OnFailure